on:
  push:
  schedule:
    - cron: "0 * * * *"

jobs:
  external_info:
    runs-on: ubuntu-latest
    name: Get external info

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Get YouTube Videos
      uses: gautamkrishnar/blog-post-workflow@master
      with:
        comment_tag_name: YOUTUBE
        max_post_count: 10
        feed_list: "https://www.youtube.com/feeds/videos.xml?channel_id=UCzR2u5RWXWjUh7CwLSvbitA"

    - name: Get DevSoutinho Project by topic on GitHub
      uses: gautamkrishnar/blog-post-workflow@master
      with:
        comment_tag_name: CHANNEL_PROJECTS
        max_post_count: 100000
        feed_list: "https://github-feed-generator.vercel.app/api/topic/devsoutinho"
        template: "$newline | $randomEmoji(💯,🔥,💫,🚀,🌮) $title $url <img src='https://gerador-de-imagens-omariosouto-alura-challenges.vercel.app/api/image-generator?url=$url'/> |"
